# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.srcs/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/lab03_vivado_bd_system_ila_0_0.xci
# IP: The module: 'lab03_vivado_bd_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/bd_a256.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a256 || ORIG_REF_NAME==bd_a256} -quiet] -quiet

# IP: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/bd_a256_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/bd_a256_ila_lib_0_ooc.xdc

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/bd_a256_ooc.xdc

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/lab03_vivado_bd_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab03_vivado_bd_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.srcs/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/lab03_vivado_bd_system_ila_0_0.xci
# IP: The module: 'lab03_vivado_bd_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/bd_a256.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a256 || ORIG_REF_NAME==bd_a256} -quiet] -quiet

# IP: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/bd_a256_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a256_ila_lib_0 || ORIG_REF_NAME==bd_a256_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/ip/ip_0/bd_a256_ila_lib_0_ooc.xdc

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/bd_0/bd_a256_ooc.xdc

# XDC: /home/sergi/Desktop/zynq_esencial/lab05/lab05_vivado/lab05_vivado.gen/sources_1/bd/lab03_vivado_bd/ip/lab03_vivado_bd_system_ila_0_0/lab03_vivado_bd_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab03_vivado_bd_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
