# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab03_vivado_bd/lab03_vivado_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab03_vivado_bd || ORIG_REF_NAME==lab03_vivado_bd} -quiet] -quiet

# IP: bd/lab03_vivado_bd/ip/lab03_vivado_bd_zynq_ultra_ps_e_0_0/lab03_vivado_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab03_vivado_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==lab03_vivado_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /home/sergi/Desktop/zynq_essencial/lab03/lab03_vivado/lab03_vivado.gen/sources_1/bd/lab03_vivado_bd/lab03_vivado_bd_ooc.xdc
