set_property SRC_FILE_INFO {cfile:/home/sergi/Desktop/zynq_esencial/lab05/resources/src/lab05_constraints.xdc rfile:../../../../resources/src/lab05_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU8        [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33    [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV8        [get_ports uart_tx]
